version: '2'
services:
  ugeplan-app:
    image: ugeplan
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://ugeplan-mariadb:3306/ugeplan?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  ugeplan-mariadb:
    extends:
      file: mariadb.yml
      service: ugeplan-mariadb
